### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by medicenplex** [somiibo/youtube-view-generator-bot#2]
![imagen](https://github.com/somiibo/youtube-view-generator-bot/assets/140880739/1093d8b3-b723-4bd2-846c-ed34623f90ac)

**Comment by sebbourgeois** [comment]
That's not a bot issue. Install nodejs (duh).

**Comment by joaquincanete** [comment]
this is a bot issue

node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module 'registry-js'
Require stack:
- D:\youtubebot\youtube-view-generator-bot\node_modules\downloads-folder\index.js
- D:\youtubebot\youtube-view-generator-bot\src\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.windows [as win32] (D:\youtubebot\youtube-view-generator-bot\node_modules\downloads-folder\index.js:43:20)
    at module.exports (D:\youtubebot\youtube-view-generator-bot\node_modules\downloads-folder\index.js:14:19)
    at module.exports (D:\youtubebot\youtube-view-generator-bot\src\index.js:14:30)
    at Object.<anonymous> (D:\youtubebot\youtube-view-generator-bot\src\index.js:50:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\youtubebot\\youtube-view-generator-bot\\node_modules\\downloads-folder\\index.js',
    'D:\\youtubebot\\youtube-view-generator-bot\\src\\index.js'
  ]
}

Node.js v18.18.0

**Comment by einstyle** [comment]
@medicenplex https://nodejs.org/en/download download, close the terminal, and run _npm install_ again
